#IOS App Details
app.bundle.id=com.saucelabs.SwagLabsMobileApp
app.file.path=iOS.Simulator.SauceLabs.Mobile.Sample.app
#app.file.path=SwagLabsMobileAppSim.zip
#app.file.path=SauceLabs-Demo-App-With-TestFairy.ipa

#Android App Details
apk.app.package=com.swaglabsmobileapp
apk.app.activity=com.swaglabsmobileapp.SplashActivity
apk.file.path=Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

#Local Appium Server Details
appium.js.path=/opt/homebrew/lib/node_modules/appium/build/lib/main.js
appium.node.path=/opt/homebrew/bin/node
appium.ip.address=127.0.0.1
appium.port=4723
appium.log.path=/target/appium_server.log

#Perfecto Server Details
perfecto.enable=true
perfecto.username=oauth-automationworldindia-7132b
perfecto.accessKey=eec77b1b-7148-445a-a875-7eb14c8fda07

#Test Configuration Details
platform.type=ios
device.profile=remote.virtual.iphone15.json